name: news_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  build_runner: ^2.4.5
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.18.6
  flutter_launcher_icons: ^0.13.1
  flutter_mobx: ^2.0.6+5
  flutter_native_splash: ^2.3.1
  http: ^1.0.0
  intl: ^0.18.1
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/img/
